[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FixedEffectModels = "9d5cd8c9-2029-5cab-9928-427838db53e3"
GLFixedEffectModels = "bafb0ae5-e5f5-5100-81b6-6a55d777c812"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Vcov = "ec2bfdc2-55df-4fc9-b9ae-4958c2cf2486"
